### ISSUE TITLE
Cookie Banner is not showing.

### ISSUE THREAD

**Issue by zcode-apps** [eyecatchup/vue-cookieconsent#2]
Hey Guys,

ive set up the plugin in my app.js (in vue3). In the console there seems like it works und starts initializing but no Cookie Banner is showing. The html source code is not changing too. How to fix?

**Comment by wwwDESIGN-basti** [comment]
ok i fix it.
You should run this in your app.js too:


`window.addEventListener('load', function () {
    // obtain cookieconsent plugin
    var cookieconsent = initCookieConsent();

    // run plugin with config object
    cookieconsent.run(consentOptions);
});
`

**Comment by zcode-apps** [comment]
ok i fix it.
You should run this in your app.js too:



```
window.addEventListener('load', function () {
    // obtain cookieconsent plugin
    var cookieconsent = initCookieConsent();

    // run plugin with config object
    cookieconsent.run(consentOptions);
});

```
